# Generated by Django 5.0.3 on 2024-03-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traindelinfinies',
            fields=[
                ('trainID', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('hour', models.CharField(max_length=5)),
            ],
        ),
    ]
