# Generated by Django 5.0.3 on 2024-03-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letraindelinfinie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traindelinfinies',
            name='plan',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
